# Generated by Django 6.0.3 on 2026-04-08 10:54

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del producto, máximo 100 caracteres', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción del producto, máximo 500 caracteres', max_length=500)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base del producto (mínimo 0.01)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='inactivo', help_text='Estado del producto (activo/inactivo)', max_length=20)),
                ('aprobado', models.BooleanField(default=False, help_text='Producto aprobado por administrador')),
                ('categoria', models.CharField(blank=True, default='', help_text='Categoría del producto', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['nombre'], name='api_product_nombre_eb8791_idx'), models.Index(fields=['estado'], name='api_product_estado_635d18_idx'), models.Index(fields=['aprobado'], name='api_product_aprobad_719c41_idx')],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(help_text='Imagen en formato JPG o PNG, máximo 2MB', upload_to='productos/%Y/%m/%d/', validators=[api.models.Imagen.validar_extension_imagen, api.models.Imagen.validar_tamaño_imagen])),
                ('es_principal', models.BooleanField(default=False, help_text='Si es TRUE, esta será la imagen principal del producto')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de la imagen en la galería')),
                ('descripcion', models.CharField(blank=True, default='', help_text='Descripción de la imagen (alt text)', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='api.producto')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['orden', 'creado_en'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('producto',), name='unique_imagen_principal_por_producto')],
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], help_text='Talla de la variante', max_length=10)),
                ('color', models.CharField(choices=[('blanco', 'Blanco'), ('negro', 'Negro'), ('rojo', 'Rojo'), ('azul', 'Azul'), ('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rosa', 'Rosa'), ('gris', 'Gris'), ('naranja', 'Naranja'), ('morado', 'Morado')], help_text='Color de la variante', max_length=20)),
                ('stock', models.IntegerField(default=0, help_text='Stock disponible (>= 0)', validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_variante', models.DecimalField(blank=True, decimal_places=2, help_text='Precio específico de variante (opcional). Si es NULL usa precio_base', max_digits=8, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='api.producto')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'unique_together': {('producto', 'talla', 'color')},
            },
        ),
    ]
